### ISSUE TITLE
Unknown plugin "babel-plugin-babel-relay-plugin-loader" specified

### ISSUE THREAD

**Issue by puruzio** [seanabrahams/graphql-relay-elixir#30]
I get the following error when starting the example app included in this repo. I looked in the brunch-config.js and other js files, but couldn't find where it specifies the plugin location as the error message suggests.

Unknown plugin "todo/node_modules/babel-plugin-babel-relay-plugin-loader" specified in "base" at 0, attempted to resolve relative to "web/static/js".

Can you please take  a look?

**Comment by seanabrahams** [comment]
@puruzio It looks like something has changed in the way babel looks for plugins. A temporary quick fix is to copy the `node_modules/babel-relay-plugin-loader` directory to `node_modules/babel-plugin-babel-relay-plugin-loader`.

From the root of the project (`todo/`) run:

``` bash
cp -r node_modules/babel-relay-plugin-loader node_modules/babel-plugin-babel-relay-plugin-loader
```

I'll look into committing a proper fix.

**Comment by puruzio** [comment]
Thanks!
