### ISSUE TITLE
GraphiQL IDE

### ISSUE THREAD

**Issue by puruzio** [seanabrahams/graphql-relay-elixir#31]
More of a question than an issue.

Is there a way to invoke the GraphiQL IDE from a URL (e.g., /graphql/) to run ad hoc queries against the graphql server?

**Comment by seanabrahams** [comment]
Yes, click on any of the links on this page http://playground.graphql-elixir.org for an example and https://github.com/graphql-elixir/hello_graphql_phoenix for the code.
