### ISSUE TITLE
integration with Absinthe Ecto (assoc)

### ISSUE THREAD

**Issue by jhonathas** [seanabrahams/graphql-relay-elixir#33]
Hi,

Is there any way to use Absinthe Ecto assoc or something similar?

Best, 
Jhonathas

**Comment by seanabrahams** [comment]
Hi @jhonathas, I'm sorry but I don't understand your question. If you're using Absinthe it looks like they have some support for Ecto as evidenced here: https://github.com/absinthe-graphql/absinthe_relay/blob/e04976408b0cffa727636608b27e04b0ca4170c4/lib/absinthe/relay/connection.ex#L321

Additionally, if you're using Absinthe they have a separate library for Relay: https://github.com/absinthe-graphql/absinthe_relay

**Comment by seanabrahams** [comment]
Going to close this. Feel free to comment if you have any further questions.
