### ISSUE TITLE
Docs on how to setup Phoenix app to reload schema.json file whenever schema related file changes

### ISSUE THREAD

**Issue by seanabrahams** [seanabrahams/graphql-relay-elixir#8]
It should be possible to watch the dir(s) that contain your GraphQL schema files and have a change trigger the recreation of the `schema.json` file automatically. Right now you can manually generate a `schema.json` file by running: `mix run GraphQL.Relay.generate_schema_json` from your Phoenix project's root directory (after you've setup some config vars).

I was hoping to find a Phoenix configuration where you can define a function to be run whenever a local file has changed. I have yet to dive into Phoenix's reloading functionality, but am aware of phoenix_live_reload's use of `:fs.subscribe()`.

**Comment by dre1080** [comment]
@seanabrahams this is what i'm currently doing:

I set up [eye_drops](https://github.com/rkotze/eye_drops) in my `config/dev.exs` like so:

Added it to my watchers list.

``` elixir
watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin"],
           mix: ["eye_drops"]]
```

``` elixir
config :eye_drops,
  tasks: [
    %{
      id: :graphql_update_schema,
      name: "Update GraphQL Schema",
      cmd: "mix graphql.gen.schema",
      paths: ["web/graph/*"] # path to graphql files
    }
  ]
```

In my `lib/mix/tasks/graphql.gen.schema`:

``` elixir
defmodule Mix.Tasks.Graphql.Gen.Schema do
  @moduledoc """
  Updates GraphQL schema.json file.
  """

  use Mix.Task

  require Logger

  @doc false
  def run(_args) do
    GraphQL.Relay.generate_schema_json

    # Update js entrypoint to force brunch to recompile
    # and load the new schema.
    # Without this line updating the schema has no effect.
    File.touch!("web/static/js/app.js")
  end
end
```

There's probably a better or simpler way to do it, but that's what I have set up so far.
Perhaps you could create a watcher for `graphql-relay-elixir` or something along those lines.

**Comment by seanabrahams** [comment]
Added Wiki page and updated README with link. Thanks @dre1080!

**Comment by dre1080** [comment]
@seanabrahams I think instead of `File.touch` you have to initiate a new `brunch build`, because it doesn't receive the schema update, so this `File.touch!("web/static/js/app.js")` becomes `System.cmd("brunch", ["build"])`. 

I think this is because the brunch watcher doesn't reload its config. So the setup for Relay's Babel Plugin doesn't update to the new schema.

**Comment by seanabrahams** [comment]
@dre1080 Ok, I'll do a proper test to confirm and update as needed. Thanks again.
